[tool.poetry]
name = "advanced-ml"
version = "1.0.0"
description = "Repository for project of Computational Intelligence Lab (263-0008-00L) offered in Spring 2021"

license = "MIT"
authors = ["András Geiszl", "Silas Walker", "Matteo Russo", "LFW Anthony"]

readme = "README.md"
repository = "https://github.com/walkersilas/CIL-Project"
homepage = "https://github.com/walkersilas/CIL-Project"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.6.4"
mypy = "^0.790"
pre-commit = "^2.9.3"
pydocstyle = "^5.1.1"
pylint = "^2.6.0"

[tool.black]
line-length = 100
